#+TITLE: 2013-FA-CS-336-LA-04-AndyS-SheaN
#+AUTHOR: Andrew Schwartzmeyer, Shea Newton
#+OPTIONS: toc:nil num:nil

| Year and Semester: | 2013 FALL                         |
| Course Number:     | CS-336                            |
| Course Title:      | Intro. to Information Assurance   |
| Work Number:       | LA-04                             |
| Work Name:         | Cross-Site Request Forgery        |
| Work Version:      | Version 1                         |
| Long Date:         | Tuesday, 10 November 2013         |
| Author Name:       | Andrew Schwartzmeyer, Shea Newton |

* TODO LA-04 NetSec  ::noexport::
   DEADLINE: <2013-11-10 Sun>
For this laboratory assignment please follow the instructions in the
laboratory in the link below and for preparing your laboratory report
please follow the instructions in this posting plus all the guidelines
posted within this course site under Course Info -> Coursework
Submission Instructions -> LA-Laboratory Report Submissions.

Cross-Site Request Forgery

Laboratory Instructions:

http://www.cis.syr.edu/~wedu/seed/Labs/Web/CSRF_Collabtive/

These laboratories have been developed by Wenliang Du of Syracuse
University and collaborators with sponsorship from the National
Science Foundation (NSF).

This is a group assignment (groups of 2 that will be determined in
class). Please submit a laboratory report as described within this
course site. Both students in the group will obtain the same grade and
only one student in the group needs to submit.

Additional Requirements:

0) When you create the VM it is mandatory that you configure the
   virtual Network to Internal Network.

VERY IMPORTANT: Before starting the laboratory please change the logon
credentials for both Ubuntu users and the mysql user.

1) In addition to describing with detail all the steps you carried out
   and their corresponding rationale and answering all the questions
   posted within the linked lab, please do the following:

2) Comment the code with high detail and include in your laboratory
   report those relevant portions of the code and their corresponding
   non-vulnerable versions.

3) Clearly specify, for example by highlighting, where the presented
   code is vulnerable.

4) Present a new version of the code that is not vulnerable, even when
   compiled and run with all compiler and system protection mechanisms
   disabled. Show, in the description and experimentally, that your
   improved version does not contain the same vulnerability.

5) Prepare and submit a laboratory report in PDF following the
   guidelines posted within this course site under Course Info ->
   Coursework Submission Instructions -> LA-Laboratory Report
   Submissions.


* Abstract

* Problem and Background

* Problem Detail

* Tasks
** Task #1: Modifying the Victim's Profile
Before we can modify the victim's profile, we need to capture a POST
request of the user submitting the edit profile form (as it is this
request we will be forging). To do this, we opened up Collabtive,
logged in as "bob", navigated to the edit profile form, opened the
Live HTTP Headers extension, cleared it, submitted the form, and went
back to the extension, which captured the initial POST request for us
(in addition to all the subsequent GET requests made by the browser
drawing the new page). The captured POST request is reproduced here,
with the GET requests removed for brevity.

#+begin_src txt
http://localhost/CSRF/Collabtive/manageuser.php?action=edit

POST /CSRF/Collabtive/manageuser.php?action=edit HTTP/1.1 Host:
localhost User-Agent: Mozilla/5.0 (X11; Linux i686; rv:5.0)
Gecko/20100101 Firefox/5.0 Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip, deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7 Connection: keep-alive
Referer:
http://localhost/CSRF/Collabtive/manageuser.php?action=editform&id=3
Cookie: PHPSESSID=88n5386bqoes4rs843oviuh731 Content-Type:
multipart/form-data;
boundary=---------------------------20367708811588547619618939618
Content-Length: 2265
-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="name"

bob -----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="userfile"; filename=""
Content-Type: application/octet-stream


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="file-$myprojects[project].ID"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="company"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="email"

bob@example.com
-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="web"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="tel1"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="tel2"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="address1"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="zip"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="address2"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="country"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="state"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="gender"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="locale"

en -----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="admin"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="oldpass"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="newpass"


-----------------------------20367708811588547619618939618
Content-Disposition: form-data; name="repeatpass"


-----------------------------20367708811588547619618939618--

HTTP/1.1 302 Found Date: Sun, 10 Nov 2013 02:02:32 GMT Server:
Apache/2.2.17 (Ubuntu) X-Powered-By: PHP/5.3.5-1ubuntu7.2 Expires:
Thu, 19 Nov 1981 08:52:00 GMT Cache-Control: no-store, no-cache,
must-revalidate, post-check=0, pre-check=0 Pragma: no-cache Location:
http://localhost/CSRF/Collabtive/manageuser.php?action=profile&id=3&mode=edited
Content-Encoding: gzip Vary: Accept-Encoding Content-Length: 26
Keep-Alive: timeout=15, max=100 Connection: Keep-Alive Content-Type:
text/html; charset=utf-8
----------------------------------------------------------
#+end_src

With the captured request, we now have the information (namely the
requests' structure and its reference to the session cookie) required
for us to forge a new one.

* Code

* Answers

* References

Du, Wenliang. 2006-2013. "Cross-Site Request Forgery (CSRF) Attack Lab". http://www.cis.syr.edu/~wedu/seed/Labs/Web/CSRF_Collabtive/
